#!/bin/bash

yum install epel-release
yum install ansible

ansible-galaxy collection install community.mysql

the_install_base='/opt'

ansible-playbook -i ansible_hosts site.yml --force-handlers --extra-var="install_base=$the_install_base"

