---
- hosts: all
  vars:
    install:
      dir: "{{ install_base }}/rr3"
      setup: "{{ install_base }}/rr3-setup"
    host:
      name: apan.manager.aaf-experimentation.cloud.edu.au
    jagger:
      version: 18
    config:
      log_threshold: 4
      encryption_key: "{{ lookup('password', install.setup + '/passwords/' + inventory_hostname + '/encryption_key chars=letters,digits length=64') }}"
      syncpass: "{{ lookup('password', install.setup + '/passwords/' + inventory_hostname + '/syncpass chars=letters,digits length=64') }}"
      support_mailto: support@apan.net
      registrationAutority: https://apan.net
    db:
      name: rr3
      username: rr3user
      password: "{{ lookup('password', install.setup + '/passwords/' + inventory_hostname + '/mariadb chars=letters,digits length=64') }}"
  tasks:
    - name: 'Verify Ansible version meets requirements'
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: "You must update Ansible to at least 2.9 to use this Ansible config for Jagger"

    - include_tasks: tasks/system.yml
    - include_tasks: tasks/php.yml
    - include_tasks: tasks/composer.yml
    - include_tasks: tasks/codeigniter.yml
    - include_tasks: tasks/db.yml
    - include_tasks: tasks/rr3.yml
    - include_tasks: tasks/apache.yml

  handlers:
    - name: Restart database
      service:
        name: mariadb
        state: restarted
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
