---
- hosts: all
  vars:
    install:
      dir: "{{ install_base }}/rr3"
    db:
      name: rr3
      username: rr3user
      password: "{{ lookup('password', install.dir + '/passwords/' + inventory_hostname + '/mariadb chars=letters,digits length=64') }}"
  tasks:
    - name: 'Verify Ansible version meets requirements'
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: "You must update Ansible to at least 2.9 to use this Ansible config for Jagger"

    - include_tasks: tasks/system.yml
    - include_tasks: tasks/php.yml
    - include_tasks: tasks/db.yml
