---

- name: 'Set script to install composer'
  templete:
    dest: '{{install.dir }}/install/install_composer.sh'
    src: 'templates/php/install_composer.sh'
    owner: root
    group: root
    mode: 0750

- name: 'Get the composer install file'
  get_url:
    url: https://getcomposer.org/installer
    dest: '{{ install.dir }}/install/install_composer'
    owner: root
    group: root
    mode: 0750

- name: 'Run the composer install script'
  command: '{{ install.dir }}/install/install_composer.sh'
    creates: '/usr/local/bin/composer'

