---
- name: 'Install epel-release and yum-utils'
  yum:
    name:
      - epel-release
      - yum-utils
    state: installed

- name: 'Install remi-release-7 for Centos 7'
  yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: installed
  when: ansible_distribution_major_version == "7"

- name: 'Install remi-release-8 for Centos 8'
  yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: installed
  when: ansible_distribution_major_version == "8"

- name: 'Use yum-config-manager to enable remi-php74'
  shell: yum-config-manager --enable remi-php74

- name: 'Install php and required libraries'
  yum:
    name:
      - php
      - php-opcache
      - php-cli
      - php-mysqlnd
      - php-mcrypt
      - php-pecl-memcached
      - php-bcmath
      - php-mbstring
      - php-xml
    state: latest

- name: 'Modify php.ini - Dont report E_WARNING'
  lineinfile:
    path: /etc/php.ini
    regexp: '^error_reporting ='
    line: 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_WARNING'

- name: 'Modify php.ini - Increase upload_max_filesize to 2G'
  lineinfile:
    path: /etc/php.ini
    regexp: '^upload_max_filesize ='
    line: 'upload_max_filesize = 2G'
