---

- name: 'Clone the rr3 repo'
  git:
    repo: 'https://github.com/Edugate/Jagger'
    dest: '{{ install.dir }}'

- name: 'Have composer install additional libraries'
  command: '/usr/local/bin/composer install'
  args:
    chdir: '{{ install.dir }}/application'
    creates: '{{ install.dir }}/application/composer.lock'

- name: 'Copy in the index.php file'
  copy:
    dest: '{{ install.dir }}/index.php'
    src: '{{ install_base }}/codeigniter/index.php'
    owner: root
    group: root
    mode: 0644
    remote_src: yes
