---

- name: 'Clone the rr3 repo'
  git:
    repo: 'https://github.com/Edugate/Jagger'
    force: yes
    dest: '{{ install.dir }}'

- name: 'Have composer install additional libraries'
  command: '/usr/local/bin/composer install'
  args:
    chdir: '{{ install.dir }}/application'
    creates: '{{ install.dir }}/application/composer.lock'

- name: 'Copy in the index.php file'
  copy:
    dest: '{{ install.dir }}/index.php'
    src: '{{ install_base }}/codeigniter/index.php'
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: 'Fix $system_path in index.php'
  replace:
    path: '{{ install.dir }}/index.php'
    regexp: "system_path = 'system';"
    replace: "system_path = '{{ install_base}}/codeigniter/system';"

- name: 'Update file composer.json'
  template:
    src: templates/rr3/composer.json
    dest: /opt/rr3/application/composer.json
    owner: apache
    group: apache
    mode: 0644

- name: 'Run the install script'
  command: '/opt/rr3/install.sh'
  args:
    chdir: /opt/rr3
    creates: /opt/rr3/logos2

- name: 'Check if composer has run'
  stat:
    path: /opt/rr3/application/composer.done
  register: composer_done

- name: 'Remove composer.lock to ensure composer runs'
  file:
    path: /opt/rr3/application/composer.lock
    state: absent
  when: composer_done.stat.exists == False

- name: 'Run composer'
  command: '/usr/local/bin/composer install'
  args:
    chdir: /opt/rr3/application
  when: composer_done.stat.exists == False

- name: 'Set composer.done'
  file:
    path: /opt/rr3/application/composer.done
    state: touch
  when: composer_done.stat.exists == False

- name: 'Set config config.php file'
  template:
    src: templates/rr3/config.php
    dest: /opt/rr3/application/config/config.php
    owner: apache
    group: apache
    mode: 0750

- name: 'Set config config_rr.php file'
  template:
    src: templates/rr3/config_rr.php
    dest: /opt/rr3/application/config/config_rr.php
    owner: root
    group: apache
    mode: 0750

- name: 'Set config database.php file'
  template:
    src: templates/rr3/database.php
    dest: /opt/rr3/application/config/database.php
    owner: root
    group: apache
    mode: 0750

- name: 'Set config email.php file'
  template:
    src: templates/rr3/email.php
    dest: /opt/rr3/application/config/email.php
    owner: root
    group: apache
    mode: 0750

- name: 'Set config memcached.php file'
  template:
    src: templates/rr3/memcached.php
    dest: /opt/rr3/application/config/memcached.php
    owner: root
    group: apache
    mode: 0750

- name: 'Check if doctrine has run'
  stat:
    path: /opt/rr3/application/doctrine.done
  register: doctrine_done

- name: 'Populate database tables'
  command: '/opt/rr3/application/doctrine orm:schema-tool:create'
  args:
    chdir: /opt/rr3/application
  when: doctrine_done.stat.exists == False

- name: 'Generate proxies'
  command: '/opt/rr3/application/doctrine orm:generate-proxies'
  args:
    chdir: /opt/rr3/application
  when: doctrine_done.stat.exists == False

- name: 'Set doctrine.done'
  file:
    path: /opt/rr3/application/doctrine.done
    state: touch
  when: doctrine_done.stat.exists == False

- name: 'Set directories writable by Apache'
  file:
    path: "/opt/rr3/application/{{ item }}"
    owner: root
    group: apache
    mode: 0770
  with_items:
    - cache
    - models/Proxies
