---

- name: 'Create base directory'
  file:
    name: '{{ install.dir }}'
    state: directory
    owner: root
    group: root
    mode: 0750

- name: 'Create install directory'
  file:
    name: '{{ install.dir }}/install'
    state: directory
    owner: root
    group: root
    mode: 0750

- name: 'Update yum packages (yum -y update)'
  yum: name=* state=latest

- name: 'Set SELinux to permissive mode'
  selinux:
    policy: targeted
    state: permissive

- name: 'Install required packages'
  yum:
    name:
      - mariadb-devel
      - mariadb
      - mariadb-server
      - chrony
    state: installed

- name: 'Install required packages - OS Version 7'
  yum:
    name:
      - MySQL-python
    state: installed
  when: ansible_distribution_major_version == "7"

- name: 'Install required packages - OS Version 8'
  yum:
    name:
      - python3-pyOpenSSL
      - python3-PyMySQL
    state: installed
  when: ansible_distribution_major_version == "8"

- name: 'Enable chrony service'
  service: name=chronyd state=started enabled=yes
