---

- name: 'Create base directory'
  file:
    name: '{{ install.dir }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 'Create setup directory'
  file:
    name: '{{ install.setup }}'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: 'Create passwords directory'
  file:
    name: '{{ install.setup }}/passwords'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: 'Update yum packages (yum -y update)'
  yum: name=* state=latest

- name: 'Set SELinux to permissive mode'
  selinux:
    policy: targeted
    state: permissive

- name: 'Install required packages'
  yum:
    name:
      - mariadb-devel
      - mariadb
      - mariadb-server
      - chrony
      - httpd
      - mod_ssl
      - unzip
      - memcached
    state: installed

- name: 'Install required packages - OS Version 7'
  yum:
    name:
      - MySQL-python
    state: installed
  when: ansible_distribution_major_version == "7"

- name: 'Install required packages - OS Version 8'
  yum:
    name:
      - python3-pyOpenSSL
      - python3-PyMySQL
    state: installed
  when: ansible_distribution_major_version == "8"

- name: 'Enable and start chrony service'
  service: name=chronyd state=started enabled=yes

- name: 'Enable and start memcached'
  service: name=memcached state=started enabled=yes
