---

- name: 'Update yum packages (yum -y update)'
  yum: name=* state=latest

- name: 'Set SELinux to permissive mode'
  selinux:
    policy: targeted
    state: permissive

- name: 'Install required packages'
  yum:
    name:
      - mariadb-devel
      - mariadb
      - mariadb-server
      - chrony
    state: installed
